wiki/encyclopedia/urls.py
from django.urls import path, re_path
from . import views


app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.title, name="title"),
    path("error/", views.title, name="error"),
    path("edit/", views.edit, name="edit"),
    path("randpage/", views.randpage, name="randpage"),
    path("add/",  views.add, name="add")
  
   ]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django import forms
from django.urls import reverse
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
import random
import markdown2
from markdown2 import Markdown

from . import util

class NewSearchForm(forms.Form):
    query = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))    

class NewPageForm(forms.Form):
    title = forms.CharField(label= 'Title')
    textarea = forms.CharField(label= 'Add Description', help_text= ' write encyclopedia content', widget=forms.Textarea(attrs={"cols": 5,"rows":10}))
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Submit'))


class NewEntryForm(forms.Form):
    textarea = forms.CharField(label= 'Add Changes', initial='', widget=forms.Textarea(attrs={"cols": 5,"rows":10}))
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Submit'))


# Create your views here.


def index(request):
    query = request.GET.get('q')
    if query:
        title, content, result = search(request, query)['query'], search(request, query)['content'], search(request, query)['result'] 
        markdowner = Markdown()  
        body = markdowner.convert(content)  
        content = body       
        return render(request, "encyclopedia/title.html", {"title":title, "content":content, "result":result}) 
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries()
        })    



def title(request, title):
    query = request.GET.get('q')
    if query:
        title, content, result = search(request, query)['query'], search(request, query)['content'], search(request, query)['result']        
        markdowner = Markdown()  
        body = markdowner.convert(content)  
        content = body
        return render(request, "encyclopedia/title.html", {"title":title, "content":content, "result":result}) 
    else:  
        content = util.get_entry(title)
        if util.get_entry(title) == None:
            return render(request, "encyclopedia/error.html")
        else:   
            markdowner = Markdown()  
            body = markdowner.convert(content)  
            content = body
            request.session['page'] = title
            page = request.session['page']
            return render(request, "encyclopedia/title.html", {
                "title":title, "content":content
            }) 
    

def search(request, query):
    lista = util.list_entries()
    result = []
    result = [i for i in lista if query.lower() in i.lower()]
    content = util.get_entry(query)
    if query in lista:
        resultado = {"query": query, "content":content, "result":""}
        return resultado
    elif result:
        resultado = {"query": "", "content":"", "result":result}
        return resultado


def add(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['textarea']
            exist = util.get_entry(title)
            if exist == None:
                util.save_entry(title, content)
                print(f"anadido, lo guardo {title}, {content}")
                markdowner = Markdown()  
                body = markdowner.convert(content)  
                content = body
                return render(request, "encyclopedia/title.html", {
                    "title":title, "content":content
                }) 
            else:
                print("Existe ya")
                return render(request, "encyclopedia/error.html")
         
        else:
            form = NewPageForm()
            return render(request, "encyclopedia/add.html", {
                "form": form
            })
            
    return render(request, "encyclopedia/add.html", {
        "form": NewPageForm()
    })
   

def edit(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['textarea']
            page = request.session['page']
            util.save_entry(page, content)
            markdowner = Markdown()  
            body = markdowner.convert(content)  
            content = body
            return render(request, "encyclopedia/title.html", {"title":page, "content":content}) 
        else:
            form = NewEntryForm()
            return render(request, "encyclopedia/edit.html", {
                "form": form
            })
    else:
        page = request.session['page']
        content = util.get_entry(page)
        print(f"aqui llego {page}, el contenido es {content}")
        form = NewEntryForm(initial={'textarea':content})
        return render(request, "encyclopedia/edit.html", {
            "form": form
        })
   
    
def randpage(request):
    query = request.GET.get('q')
    if query:
        title, content, result = search(request, query)['query'], search(request, query)['content'], search(request, query)['result']  
        markdowner = Markdown()  
        body = markdowner.convert(content)  
        content = body      
        return render(request, "encyclopedia/title.html", {"title":title, "content":content, "result":result}) 
    else:
        return render(request, "encyclopedia/randpage.html", {
            "entry": random.choice(util.list_entries())
        })

wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    
    <h1>Create Encyclopedia New Entry</h1>
    <div style = "max-width:600px;">
        {% load crispy_forms_tags %}
            
            {% csrf_token %}
           
  
        {% crispy form %}
    </div>


{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}
{% block search %}
    

    
{% endblock %}}
    
{% block body %}
    <h1>Edit Encyclopedia Entry</h1>
            

        <div style = "max-width:600px; min-height: 600px;">
           
            {% load crispy_forms_tags %}
    
                {% csrf_token %}
                
    
            {% crispy form %}
        </div>


{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}}

{% block body%}
    <h1>Error</h1>
   
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}
{% block search %}
    

    
{% endblock %}}


{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/{{entry}}"> {{ entry }}</a></li>
        {% endfor %}
    </ul>



{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="GET">
                    <input class="search" type="text" name="q" placeholder="busca Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randpage' %}">Random Page</a> 
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/randpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}
{% block search %}
    

    
{% endblock %}}


{% block body %}
    <h1>Random Page</h1>

    <ul>
        
            <li><a href="/{{ entry }}"> {{ entry }}</a></li>
        
    </ul>



{% endblock %}

wiki/encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}



{% block body %}
{% if title %}
   
    <p> {{ content|safe }}  </p>
    <form action="{% url 'encyclopedia:edit' %}">
        {% csrf_token %}
        <button class="btn btn-primary" type="text" name="title" label="edit" value="{{ title }}">Edit</button> 
        
    </form>

{% endif %}
{% if result %}  
<h3>Results of your search...</h3>
    <p></p>
    <ul>
        {% for res in result %}
            <li><a href="/{{ res }}"> {{ res }}</a></li>
        {% endfor %}
    </ul>
    
{% endif %}
{% endblock %}